tools/convert: print reasonable error error
if eg. input file doesn't exist, something like:

    terminate called after throwing an instance of 'std::__ios_failure'
      what():  basic_ios::clear: iostream error

was presented which isn't much helpful so catch the error and print
textual representation of errno so that the error becomes:

    ERROR: basic_ios::clear: iostream error: No such file or directory