CI mac: enforce use of Qt5 even if Qt6 present
fixes failed run
<https://github.com/CESNET/UltraGrid/actions/runs/5925739298/job/16065753514>

From some point, it seems that Qt6 (Homebrew port _qt_) is already
installed but it doesn't bundle successfully. So enforce using Qt5
(previous symlink command didn't replace the `/usr/local/opt/qt` symlink
if already present).

\+ copy the link instead of linking it to prevent:

    Error: /usr/local/opt/qt@5 is not a valid keg