handle_error: print reason if trigerred + stcktrce
- print reason if trigerred to notify user that the reason to exit was
its request but UG won't exit otherwise
- print the stacktrace in this case - this may help when developing or
if the user wants to report the problem so that it might be attached