fixed new zfec still crashing in Win
imroves 2af4ace25 fix, which didn't work for Windows, since the compiler
here doesn't accept include with absolute path:
```
tst.c:4:10: fatal error: '/usr/local/src/zfec/fec.h' file not found
    4 | #include "/usr/local/src/zfec/fec.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

(neither <> syntax works)